### ISSUE TITLE
Hard-coded bit index in Svnapot

### ISSUE THREAD

**Issue by quxfred** [riscv/virtual-memory#1]
Hi,

Just spot this in the address-translation algorithm description just above the ending paragraphs of normative text.  Sorry I can't find the source therefore can't really post a link to it. I supposed the "9" in the square brackets below only applies to SV32?

> j[9 : napot_bits] = i[9 : napot_bits],

To make it generic enough to apply to SV39/SV48 etc, perhaps better to change it to vpn_bits-1 or simply vpn_msb?

Regards,
Freddie

**Comment by daniellustig** [comment]
The 9 in that equation refers to the size of VPN[0] and PPN[0] on Sv39/48/57, not to anything in Sv32.  Svnapot only applies to Sv39/48/57, as Sv32 PTEs have no reserved bits available.

**Comment by quxfred** [comment]
Good point. So the VPN field is 9-bit wide.

But surely the MSB of a 9-bit field is at bit position 8, if you count from 0? Have I overlooked anything here?

**Comment by daniellustig** [comment]
Fix pushed in https://github.com/riscv/riscv-isa-manual/pull/628
